// deno-lint-ignore-file
// .densky/http/convention/index/_index.ts
// THIS FILE WAS GENERATED BY DENSKY-BACKEND (by Apika Luca)
import * as $Densky$ from "densky";

async function handler(
  req: $Densky$.HTTPRequest,
): Promise<$Densky$.HTTPPossibleResponse> {
  const urlMatcherPrepare_pathname = req.pathname;

  if (urlMatcherPrepare_pathname === "/convention/index") {
    if (urlMatcherPrepare_pathname === "/convention/index") {
      if (req.method === "GET") {
        await req.prepare();

        return new Response("INDEX: Matched " + req.pathname);
      }

      return new $Densky$.HTTPError($Densky$.StatusCode.NOT_METHOD)
        .toResponse();
    }
  }
}

export default handler;
