// deno-lint-ignore-file
// .densky/http/convention/middleware/_middleware.ts
// THIS FILE WAS GENERATED BY DENSKY-BACKEND (by Apika Luca)
import * as $Densky$ from "densky";

async function handler(
  req: $Densky$.HTTPRequest,
): Promise<$Densky$.HTTPPossibleResponse> {
  const urlMatcherPrepare_pathname = req.pathname;

  if (urlMatcherPrepare_pathname === "/convention/middleware/_middleware") {
    if (req.method === "GET") {
      await req.prepare();

      if (req.url.searchParams.has("mid")) {
        return new Response("MIDDLEWARE: Matched " + req.pathname);
      }
    }
  }
}

export default handler;
