// deno-lint-ignore-file
// .densky/ws/_connect.ts
// THIS FILE WAS GENERATED BY DENSKY-BACKEND (by Apika Luca)
import * as $Densky$ from "densky";

import { Socket } from "densky";

async function handler(
  _: $Densky$.SocketCtx,
  socket: $Densky$.Socket,
): Promise<void> {
  const urlMatcherPrepare_pathname = _.req.pathname;

  if (urlMatcherPrepare_pathname === "/_connect") {
    console.log("Socket is connected:", socket.id);
  }
}

export default handler;
