// deno-lint-ignore-file
// .densky/ws/_disconect.ts
// THIS FILE WAS GENERATED BY DENSKY-BACKEND (by Apika Luca)
import * as $Densky$ from "densky";

async function handler(
  ctx: $Densky$.SocketCtx,
  sock: $Densky$.Socket,
): Promise<void> {
  const urlMatcherPrepare_pathname = ctx.req.pathname;

  if (urlMatcherPrepare_pathname === "/_disconect") {
    console.log("Socket is disconected");
  }
}

export default handler;
