// deno-lint-ignore-file
// .densky/ws/index.ts
// THIS FILE WAS GENERATED BY DENSKY-BACKEND (by Apika Luca)
import * as $Densky$ from "densky";

import $connectHandler$ from "./_connect.ts";
import $disconectHandler$ from "./_disconect.ts";

async function handler(
  ctx: $Densky$.SocketCtx,
  sock: $Densky$.Socket,
): Promise<void> {
  const urlMatcherPrepare_pathname = ctx.req.pathname;

  const raw = sock.raw;
  raw.onopen = () => {
    ctx.queueSockets.delete(sock);
    const id = ctx.addSocket(sock);

    sock.sendRaw($Densky$.SocketMessageEnum.DENSKY_CONNECT, id);
    // Compatiblity for router, this is more simple than
    // try to changer the router
    ctx.req.pathname = "/_connect";
    $connectHandler$(ctx, sock);
  };
  raw.onmessage = (e) => {
    console.log(e);
  };
  raw.onclose = (e) => {
    ctx.sockets.delete(sock.id);
    // Compatiblity for router, this is more simple than
    // try to changer the router
    ctx.req.pathname = "/_disconect";
    $disconectHandler$(ctx, sock);
  };
}

export default handler;
