import { fs, pathMod } from "../../deps.ts";
import { toResponseFnDecl } from "../../utils.ts";
import { HttpRoutesTree } from "./HttpRoutesTree.ts";
import { CompileOptions } from "../types.ts";

export async function httpWrite(
  tree: HttpRoutesTree,
  opts: Required<CompileOptions>,
) {
  await tree.writeFileIncremental();

  {
    // dusky.main.ts
    const mainPath = pathMod.join(opts.outDir, "http.main.ts");
    await fs.ensureFile(mainPath);
    await Deno.writeTextFile(
      mainPath,
      `// THIS FILE WAS GENERATED BY DUSKY-BACKEND (By Apika Luca)
import * as $Dusky$ from "dusky";
import mainHandler from "./http/index.ts";

${toResponseFnDecl()}

export default async function requestHandler(req: Deno.RequestEvent, conn: Deno.Conn): Promise<Response> {
  return toResponse(await mainHandler(new $Dusky$.HTTPRequest(req)) ?? new $Dusky$.HTTPError($Dusky$.StatusCode.NOT_FOUND));
}`,
    );
  }
}
