// .dusky/bye/_fallback.ts
// THIS FILE WAS GENERATED BY DUSKY-BACKEND (by Apika Luca)
import * as $Dusky$ from "dusky"
import { HTTPRequest, IController } from "dusky"

async function handler(req: $Dusky$.HTTPRequest) {
  if (req.pathname === "bye/_fallback") {
    if (req.method === "GET") {
      let _req = httpRequest
      return new Response("Bye " + _req.event.request.url)
    }

    return new $Dusky$.HTTPError($Dusky$.StatusCode.NOT_METHOD)
  }
}

export default handler
