// .dusky/user/[id].ts
// THIS FILE WAS GENERATED BY DUSKY-BACKEND (by Apika Luca)
import * as $Dusky$ from "dusky"
import { IController } from "dusky"

async function handler(req: $Dusky$.HTTPRequest) {
  if (req.pathname === "user/[id]") {
    if (req.method === "GET") {
      return new Response("USER")
    }

    return new $Dusky$.HTTPError($Dusky$.StatusCode.NOT_METHOD)
  }
}

export default handler
