// deno-lint-ignore-file
// .densky/http/convention/url-params/[p2].ts
// THIS FILE WAS GENERATED BY DENSKY-BACKEND (by Apika Luca)
import * as $Densky$ from "densky";
import $child$0 from "./[p2]/deep.ts";

const urlMatcherSerial_pathname = [{ raw: "convention", isVar: false }, {
  raw: "url-params",
  isVar: false,
}, { raw: "[p2]", isVar: true, varname: "p2" }];

async function handler(
  req: $Densky$.HTTPRequest,
): Promise<$Densky$.HTTPPossibleResponse> {
  const urlMatcherPrepare_pathname = req.byParts;
  if (
    (() => {
      const t = urlMatcherPrepare_pathname;
      const p = urlMatcherSerial_pathname;

      if (t.length < p.length) return false;
      return p.every((tp, i) => {
        if (!t[i]) return false;
        if (tp.isVar) return true;
        if (tp.raw === t[i]) return true;
        return false;
      });
    })()
  ) {
    const out$0 = await $child$0(req);
    if (out$0) return out$0;
  }
}

export default handler;
