// THIS FILE WAS GENERATED BY DUSKY-BACKEND (By Apika Luca)
import { HTTPRequest, HTTPError } from "dusky";
import { StatusCode } from "dusky/common.ts";
import mainHandler from "./index.ts";

export default async function requestHandler(req: Deno.RequestEvent, conn: Deno.Conn): Promise<Response> {
  return mainHandler(new HTTPRequest(req)) ?? new HTTPError(StatusCode.NOT_FOUND).toResponse();
}