// THIS FILE WAS GENERATED BY DUSKY-BACKEND
import handler$0 from "./bye/_fallback.ts";
import handler$1 from "./hello.ts"

export default async function requestHandler(req: Deno.RequestEvent, conn: Deno.Conn): Promise<Response> {
  return new Response("Hola")
}