// .dusky/index.ts
// THIS FILE WAS GENERATED BY DUSKY-BACKEND (by Apika Luca)
import * as $Dusky$ from "dusky"
import { IController } from "dusky"
import $child$0 from "./bye/_fallback.ts"
import $child$1 from "./hello.ts"
import $child$2 from "./user/[id].ts"

async function handler(req: $Dusky$.HTTPRequest) {
  if (true) {
    if (req.method === "GET") {
      return new Response("Index")
    }

    return new $Dusky$.HTTPError($Dusky$.StatusCode.NOT_METHOD)
  }
}

export default handler
