// deno-lint-ignore-file
// .densky/http/feats/dynamic/[param].ts
// THIS FILE WAS GENERATED BY DENSKY-BACKEND (by Apika Luca)
import * as $Densky$ from "densky";

import { HTTPResponse } from "densky";

const urlMatcherSerial_pathname = [{ raw: "feats", isVar: false }, {
  raw: "dynamic",
  isVar: false,
}, { raw: "[param]", isVar: true, varname: "param" }];

async function handler(
  req: $Densky$.HTTPRequest,
): Promise<$Densky$.HTTPPossibleResponse> {
  const urlMatcherPrepare_pathname = req.byParts;

  if (
    (() => {
      const t = urlMatcherPrepare_pathname;
      const p = urlMatcherSerial_pathname;
      const m = req.params;

      if (t.length !== p.length) return false;
      m.clear();
      return t.every((tp, i) => {
        if (!p[i]) return false;
        if (p[i].isVar) {
          m.set(p[i].varname, tp);
          return true;
        }
        if (p[i].raw === tp) return true;
        return false;
      });
    })()
  ) {
    if (
      (() => {
        const t = urlMatcherPrepare_pathname;
        const p = urlMatcherSerial_pathname;
        const m = req.params;

        if (t.length !== p.length) return false;
        m.clear();
        return t.every((tp, i) => {
          if (!p[i]) return false;
          if (p[i].isVar) {
            m.set(p[i].varname, tp);
            return true;
          }
          if (p[i].raw === tp) return true;
          return false;
        });
      })()
    ) {
      if (req.method === "GET") {
        await req.prepare();

        const condition =
          (req.url.searchParams.get("condition") || "true") === "true";
        const param = req.params.get("param") || "PARAM";
        const num = parseInt(req.url.searchParams.get("num") || "0") || 0;

        return await HTTPResponse.view("dynamic.html", {
          condition,
          param,
          num,
          title: "Dynamic",
        });
      }

      return new $Densky$.HTTPError($Densky$.StatusCode.NOT_METHOD)
        .toResponse();
    }
  }
}

export default handler;
