// deno-lint-ignore-file
// .densky/http/convention.ts
// THIS FILE WAS GENERATED BY DENSKY-BACKEND (by Apika Luca)
import * as $Densky$ from "densky";
import $child$2 from "./convention/fallback.ts";
import $child$1 from "./convention/index/_index.ts";
import $child$0 from "./convention/middleware/_index.ts";
import $child$3 from "./convention/url-params.ts";

async function handler(
  req: $Densky$.HTTPRequest,
): Promise<$Densky$.HTTPPossibleResponse> {
  const urlMatcherPrepare_pathname = req.pathname;
  if (urlMatcherPrepare_pathname.startsWith("/convention")) {
    const out$0 = await $child$0(req);
    if (out$0) return out$0;
    const out$1 = await $child$1(req);
    if (out$1) return out$1;
    const out$2 = await $child$2(req);
    if (out$2) return out$2;
    const out$3 = await $child$3(req);
    if (out$3) return out$3;
  }
}

export default handler;
