// deno-lint-ignore-file
// .densky/http/index.ts
// THIS FILE WAS GENERATED BY DENSKY-BACKEND (by Apika Luca)
import * as $Densky$ from "densky";
import $child$1 from "./convention.ts";
import $child$0 from "./feats.ts";
import $child$3 from "./out.ts";
import $child$2 from "./test.ts";

import { HTTPResponse } from "densky";

async function handler(
  req: $Densky$.HTTPRequest,
): Promise<$Densky$.HTTPPossibleResponse> {
  const urlMatcherPrepare_pathname = req.pathname;
  const out$0 = await $child$0(req);
  if (out$0) return out$0;
  const out$1 = await $child$1(req);
  if (out$1) return out$1;
  const out$2 = await $child$2(req);
  if (out$2) return out$2;
  const out$3 = await $child$3(req);
  if (out$3) return out$3;

  if (urlMatcherPrepare_pathname === "/") {
    if (req.method === "GET") {
      await req.prepare();

      return await HTTPResponse.view("index.html");
    }

    return new $Densky$.HTTPError($Densky$.StatusCode.NOT_METHOD).toResponse();
  }
}

export default handler;
