// deno-lint-ignore-file
// .densky/http/test.ts
// THIS FILE WAS GENERATED BY DENSKY-BACKEND (by Apika Luca)
import * as $Densky$ from "densky";

import { HTTPResponse } from "densky";

async function handler(
  req: $Densky$.HTTPRequest,
): Promise<$Densky$.HTTPPossibleResponse> {
  const urlMatcherPrepare_pathname = req.pathname;

  if (urlMatcherPrepare_pathname === "/test") {
    if (urlMatcherPrepare_pathname === "/test") {
      if (req.method === "GET") {
        await req.prepare();

        return await HTTPResponse.view("index.html");
      }

      return new $Densky$.HTTPError($Densky$.StatusCode.NOT_METHOD)
        .toResponse();
    }
  }
}

export default handler;
