// deno-lint-ignore-file
// .densky/http/convention/url-params.ts
// THIS FILE WAS GENERATED BY DENSKY-BACKEND (by Apika Luca)
import * as $Densky$ from "densky";
import $child$2 from "./url-params/[p1].ts";
import $child$1 from "./url-params/[p2].ts";
import $child$0 from "./url-params/route.ts";

async function handler(
  req: $Densky$.HTTPRequest,
): Promise<$Densky$.HTTPPossibleResponse> {
  const urlMatcherPrepare_pathname = req.pathname;
  if (urlMatcherPrepare_pathname.startsWith("/convention/url-params")) {
    const out$0 = await $child$0(req);
    if (out$0) return out$0;
    const out$1 = await $child$1(req);
    if (out$1) return out$1;
    const out$2 = await $child$2(req);
    if (out$2) return out$2;
  }
}

export default handler;
