// deno-lint-ignore-file
// .densky/http/feats/cookies/_index.ts
// THIS FILE WAS GENERATED BY DENSKY-BACKEND (by Apika Luca)
import * as $Densky$ from "densky";
import $child$0 from "./get.ts";

async function handler(
  req: $Densky$.HTTPRequest,
): Promise<$Densky$.HTTPPossibleResponse> {
  const urlMatcherPrepare_pathname = req.pathname;
  if (urlMatcherPrepare_pathname.startsWith("/feats/cookies")) {
    const out$0 = await $child$0(req);
    if (out$0) return out$0;

    if (urlMatcherPrepare_pathname === "/feats/cookies") {
      if (urlMatcherPrepare_pathname === "/feats/cookies") {
        if (req.method === "GET") {
          await req.prepare();

          return Response.json(req.cookies.raw);
        }

        return new $Densky$.HTTPError($Densky$.StatusCode.NOT_METHOD)
          .toResponse();
      }
    }
  }
}

export default handler;
