// deno-lint-ignore-file
// .densky/http/feats/cookies/get.ts
// THIS FILE WAS GENERATED BY DENSKY-BACKEND (by Apika Luca)
import * as $Densky$ from "densky";
import $child$0 from "./get/[name].ts";

async function handler(
  req: $Densky$.HTTPRequest,
): Promise<$Densky$.HTTPPossibleResponse> {
  const urlMatcherPrepare_pathname = req.pathname;
  if (urlMatcherPrepare_pathname.startsWith("/feats/cookies/get")) {
    const out$0 = await $child$0(req);
    if (out$0) return out$0;
  }
}

export default handler;
