import { fs, pathMod } from "../../deps.ts";
import { CompileOptions } from "../types.ts";
import { format } from "../formatter.ts";
import { StaticFileTree } from "./StaticFileTree.ts";

export async function staticWrite(
  tree: StaticFileTree,
  opts: Required<CompileOptions>
) {
  if (opts.staticPath === false) return;

  const nodes: string[] = [];

  tree.files.forEach((node) => {
    const staticFile = `new $Densky$.StaticFileNode("${node.urlPath}", "${node.filePath}", staticTree.staticFiles)`;
    nodes.push(`staticTree.files.set("${node.urlPath}", ${staticFile});`);
  });

  {
    // static.main.ts
    const mainPath = pathMod.join(opts.outDir, "static.main.ts");
    await fs.ensureFile(mainPath);
    const content = `// THIS FILE WAS GENERATED BY DENSKY-BACKEND (By Apika Luca)
import * as $Densky$ from "densky";

const staticTree = new $Densky$.StaticFileTree("${opts.staticPath}");
${nodes.join("\n")}

export default function requestHandler(req: $Densky$.HTTPRequest): Promise<Response | null> {
  return staticTree.handleRequest(req.pathname);
}`;
    await Deno.writeTextFile(mainPath, format(mainPath, content));
  }
}
