// THIS FILE WAS GENERATED BY DENSKY-BACKEND (By Apika Luca)
import * as $Densky$ from "densky";
import mainHandler from "./http/index.ts";

function toResponse(
  req: $Densky$.HTTPRequest,
  response:
    | $Densky$.HTTPResponse
    | Response
    | $Densky$.HTTPError
    | Error
    | void,
): Response {
  if (response instanceof $Densky$.HTTPResponse) {
    return new Response("Teapot (ToResponse)");
  }

  if (response instanceof Error) {
    response = $Densky$.HTTPError.fromError(response);
  }

  if (response instanceof $Densky$.HTTPError) {
    response = response.toResponse();
  }

  if (response instanceof Response) {
    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers: Object.fromEntries([
        ...req.headers.entries(),
        ...response.headers.entries(),
      ]),
    });
  }

  throw new Error("Unreachable code");
}

export default async function requestHandler(
  req: $Densky$.HTTPRequest,
): Promise<Response> {
  return toResponse(
    req,
    await mainHandler(req)
      ?? new $Densky$.HTTPError($Densky$.StatusCode.NOT_FOUND),
  );
}
