// THIS FILE WAS GENERATED BY DENSKY-BACKEND (By Apika Luca)
import * as $Densky$ from "densky";
import httpHandler from "./http.main.ts";
import staticHandler from "./static.main.ts";
import wsHandler from "./ws.main.ts";

import $view$2 from "./views/dynamic.html.ts";
import $view$1 from "./views/index.html.ts";

$Densky$.HTTPResponse.viewsTree = new $Densky$.DynamicHtmlTree(
  "src/views",
  ".densky",
);
{
  const filePath = $Densky$.DenskyHtmlRuntime.resolve(
    $Densky$.Globals.cwd,
    "src/views/index.html",
  );
  const outPath = $Densky$.DenskyHtmlRuntime.resolve(
    $Densky$.Globals.cwd,
    ".densky/views/index.html",
  );
  const node = new $Densky$.DynamicHtmlTreeNode(filePath, outPath);
  $Densky$.HTTPResponse.viewsTree.tree.set("index.html", node);
  node.render = $view$1;
}
{
  const filePath = $Densky$.DenskyHtmlRuntime.resolve(
    $Densky$.Globals.cwd,
    "src/views/dynamic.html",
  );
  const outPath = $Densky$.DenskyHtmlRuntime.resolve(
    $Densky$.Globals.cwd,
    ".densky/views/dynamic.html",
  );
  const node = new $Densky$.DynamicHtmlTreeNode(filePath, outPath);
  $Densky$.HTTPResponse.viewsTree.tree.set("dynamic.html", node);
  node.render = $view$2;
}

export default async function requestHandler(
  request: Deno.RequestEvent,
  conn: Deno.Conn,
): Promise<Response> {
  const req = new $Densky$.HTTPRequest(request);

  const staticRes = await staticHandler(req);
  if (staticRes) return staticRes;

  const wsRes = await wsHandler(req);
  if (wsRes) return wsRes;

  return await httpHandler(req);
}
