// THIS FILE WAS GENERATED BY DENSKY-BACKEND (By Apika Luca)
import * as $Densky$ from "densky";

const staticTree = new $Densky$.StaticFileTree("src/static", "static");
staticTree.files.set(
  "/static/text.txt",
  new $Densky$.StaticFileNode(
    "/static/text.txt",
    "text.txt",
    staticTree.staticFiles,
  ),
);
staticTree.files.set(
  "/static/styles.css",
  new $Densky$.StaticFileNode(
    "/static/styles.css",
    "styles.css",
    staticTree.staticFiles,
  ),
);
staticTree.files.set(
  "/static/robots.txt",
  new $Densky$.StaticFileNode(
    "/static/robots.txt",
    "robots.txt",
    staticTree.staticFiles,
  ),
);

export default function requestHandler(
  req: $Densky$.HTTPRequest,
): Promise<Response | null> {
  return staticTree.handleRequest(req.pathname);
}
