// THIS FILE WAS GENERATED BY DENSKY-BACKEND (By Apika Luca)
import * as $Densky$ from "densky";
import mainHandler from "./ws/index.ts";

const ctx = new $Densky$.SocketCtx();

export default async function requestHandler(
  req: $Densky$.HTTPRequest,
): Promise<Response | null> {
  if (req.pathname === "/ws") {
    if (req.raw.headers.get("upgrade") !== "websocket") {
      return null;
    }

    const { socket: socketRaw, response } = Deno.upgradeWebSocket(req.raw);
    const socket = new $Densky$.Socket(socketRaw);

    ctx.queueSockets.add(socket);
    ctx.req = req;
    mainHandler(ctx, socket);

    return response;
  }

  return null;
}
